// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using supermarket.DBcontext;

#nullable disable

namespace supermarket.Migrations
{
    [DbContext(typeof(SupermarketProductDBcontext))]
    [Migration("20230607130157_MyFirstMigrati")]
    partial class MyFirstMigrati
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("supermarket.EntityModel.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("int");

                    b.Property<int>("SupermarketId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("SupermarketId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("supermarket.EntityModel.Supermarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("supermarkets");
                });

            modelBuilder.Entity("supermarket.EntityModel.Product", b =>
                {
                    b.HasOne("supermarket.EntityModel.Supermarket", "Supermarketi")
                        .WithMany("Porductebi")
                        .HasForeignKey("SupermarketId");

                    b.Navigation("Supermarketi");
                });

            modelBuilder.Entity("supermarket.EntityModel.Supermarket", b =>
                {
                    b.Navigation("Porductebi");
                });
#pragma warning restore 612, 618
        }
    }
}
